/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2020;

import advent_of_code_2020.day_6.ResponseAnalyzer;
import advent_of_code_2020.utils.FileHelper;

public class App {

    public static void main(String[] args) {
        String filePath = "/Users/vikramsingh/work/advent_of_code_2020/src/main/resources/customDeclarationFormResponse.txt";
        FileHelper fileHelper = new FileHelper(filePath);
        String inputs = fileHelper.getInputs();
        ResponseAnalyzer responseAnalyzer = new ResponseAnalyzer(inputs);
        System.out.println(responseAnalyzer.getPositiveResponseCount());
    }
}
